# base image
FROM node:16.13.1

ENV NODE_ENV development

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g nodemon@1.17.1

CMD [ "npm", "run", "start:dev" ]
